# Generated by Django 3.2.7 on 2021-09-23 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210923_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinf',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'м'), ('W', 'ж')], max_length=1, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 15, 6, 38, 102069, tzinfo=utc)),
        ),
    ]
