# Generated by Django 3.2.7 on 2021-10-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='created_times',
            new_name='created_timestamp',
        ),
    ]
