# Generated by Django 3.2.7 on 2021-10-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='is_active',
        ),
    ]
